### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-jquery-research-and-scale#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://alive-print.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/jquery-research-and-scale/1) criteria:
- [x] Three inputs are used to calculate what each person on the road trip should contribute to gas: mileage rate, total miles, number of riders
- [x] Mileage rate should start at 0.5 (50 cents), with a minimum value of 0.1
- [x] Total miles should start at 0, with a minimum value of 0
- [x] Number of riders should start at 1, with a minimum value of 1 and maximum value of 5
- [x] The calculated share per person should be: total miles \* mileage rate / number of riders
- [x] The element that displays the resulting calculation (which I'll call "the result element") should start out displaying "$0.00", then continue to display a dollar amount in that format as the number increases
- [x] The result element should update in real time, as the contributing inputs change
- [x] The result element should have an "expensive" class if the result is greater than or equal to 50

**Comment by chrisvfritz** [comment]
[These two lines](https://github.com/KatieMFritz/codelab-jquery-research-and-scale/blob/master/calculator.js#L14-L15) can actually be shortened to a single, much simpler one:

``` js
} else {
```

:smiley: 

Also, it looks like in Chrome on OS X, the input `min` and `max` validations aren't working. Can you investigate why?

**Comment by KatieMFritz** [comment]
Fixed that line.

The min and max are more a UX guideline. If someone wants to put in different numbers, so be it. GIVE ME A SQUIRREL.

**Comment by chrisvfritz** [comment]
:shipit:
